######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 13 17:00:51 2011
######################################################################

DESTDIR = /u4/home/pkarasev3/source/kslice/src/build.wolverine/bin
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp
