######################################################################
# Automatically generated by qmake (2.01a) Tue May 10 20:08:18 2011
######################################################################

DESTDIR = /u4/home/pkarasev3/source/KSlice-dev/kslice/source/build.wolverine.debug/bin
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h
FORMS += gui.ui
SOURCES += gui.cpp main.cpp
